# Generated by Django 4.1.7 on 2023-03-04 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contacs',
            new_name='Contacts',
        ),
    ]
