# Generated by Django 4.1.7 on 2023-03-04 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_rename_contacs_contacts'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacts',
            name='show',
            field=models.BooleanField(default=True),
        ),
    ]
