# Generated by Django 4.1.7 on 2023-03-09 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_contacts_show'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacts',
            name='photo',
            field=models.ImageField(blank=True, upload_to='photos/%Y/%m'),
        ),
    ]
